chrome:
  image: selenium/standalone-chrome-debug:2.53.0
  ports:
    - "4444:4444"
    - "5900:5900"
  environment:
    - SCREEN_WIDTH=1280
    - SCREEN_HEIGHT=1024
    - SCREEN_DEPTH=16
artstack-test:
  image: kitfung/artstack-test-beta
  links:
    - chrome